# Generated by Django 5.2.15 on 2026-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.CharField(max_length=255)),
                ('concept_code', models.CharField(max_length=50)),
                ('domain_id', models.CharField(choices=[('Gender', 'Gender'), ('Race', 'Race'), ('Condition', 'Condition'), ('Drug', 'Drug'), ('Measurment', 'Measurment'), ('Visit', 'Visit'), ('Procedure', 'Procedure'), ('Metadata', 'Metadata')], max_length=20)),
                ('vocabulary_id', models.CharField(choices=[('SNOMED', 'SNOMED-CT'), ('ICD10', 'ICD-10'), ('RxNorm', 'RxNorm'), ('LOINC', 'LOINC'), ('GENDER', 'Gender'), ('RACE', 'Race')], max_length=20)),
                ('valid_start_date', models.DateField(default='1900-01-01')),
                ('valid_end_date', models.DateField(default='2099-12-31')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'omop_concept',
            },
        ),
    ]
