# Generated by Django 5.2.15 on 2026-06-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_birth', models.IntegerField()),
                ('month_of_birth', models.IntegerField(blank=True, null=True)),
                ('day_of_birth', models.IntegerField(blank=True, null=True)),
                ('person_source_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender_concept', models.ForeignKey(limit_choices_to={'vocabulary_id': 'GENDER'}, on_delete=django.db.models.deletion.PROTECT, related_name='persons_gender', to='data.concept')),
                ('race_concept', models.ForeignKey(blank=True, limit_choices_to={'vocabulary_id': 'Race'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_race', to='data.concept')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'omop_person',
            },
        ),
    ]
