# Generated by Django 5.2.15 on 2026-06-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('visit_occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_start_date', models.DateField(db_index=True)),
                ('visit_end_date', models.DateField(blank=True, null=True)),
                ('visit_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='data.person')),
                ('visit_concept', models.ForeignKey(limit_choices_to={'domain_id': 'Visit'}, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='data.concept')),
            ],
            options={
                'db_table': 'omop_visit_occurrence',
            },
        ),
    ]
