# Generated by Django 5.2.15 on 2026-06-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_visitoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityLog',
            fields=[
                ('quality_id', models.AutoField(primary_key=True, serialize=False)),
                ('checked_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_visits', models.IntegerField(default=0)),
                ('total_conditions', models.IntegerField(default=0)),
                ('total_medications', models.IntegerField(default=0)),
                ('total_measurements', models.IntegerField(default=0)),
                ('patients_with_conditions', models.IntegerField(default=0)),
                ('patients_with_medications', models.IntegerField(default=0)),
                ('patients_with_measurements', models.IntegerField(default=0)),
                ('conditions_with_null_concept', models.IntegerField(default=0)),
                ('medications_with_null_concept', models.IntegerField(default=0)),
                ('invalid_date_ranges', models.IntegerField(default=0)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Data Quality Log',
                'verbose_name_plural': 'Data Quality Logs',
                'db_table': 'omop_data_quality_log',
                'ordering': ['-checked_date'],
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_name', models.CharField(default='Unknown', max_length=100)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ETL Log',
                'verbose_name_plural': 'ETL Logs',
                'db_table': 'omop_etl_log',
                'ordering': ['-run_time'],
            },
        ),
        migrations.AlterField(
            model_name='concept',
            name='domain_id',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Race', 'Race'), ('Condition', 'Condition'), ('Drug', 'Drug'), ('Measurement', 'Measurement'), ('Visit', 'Visit'), ('Procedure', 'Procedure'), ('Metadata', 'Metadata')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='race_concept',
            field=models.ForeignKey(blank=True, limit_choices_to={'vocabulary_id': 'RACE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_race', to='data.concept'),
        ),
        migrations.CreateModel(
            name='ObservationPeriod',
            fields=[
                ('observation_period_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_period_start_date', models.DateField()),
                ('observation_period_end_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_periods', to='data.person')),
            ],
            options={
                'verbose_name': 'Observation Period',
                'verbose_name_plural': 'Observation Periods',
                'db_table': 'omop_observation_period',
            },
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('condition_occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_start_date', models.DateField(db_index=True)),
                ('condition_end_date', models.DateField(blank=True, null=True)),
                ('condition_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_concept', models.ForeignKey(limit_choices_to={'domain_id': 'Condition'}, on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='data.concept')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='data.person')),
                ('visit_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='data.visitoccurrence')),
            ],
            options={
                'verbose_name': 'Condition Occurrence',
                'verbose_name_plural': 'Condition Occurrences',
                'db_table': 'omop_condition_occurrence',
                'indexes': [models.Index(fields=['person', 'condition_start_date'], name='omop_condit_person__655358_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrugExposure',
            fields=[
                ('drug_exposure_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_exposure_start_date', models.DateField(db_index=True)),
                ('drug_exposure_end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_supply', models.IntegerField(blank=True, null=True)),
                ('drug_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_concept', models.ForeignKey(limit_choices_to={'domain_id': 'Drug'}, on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='data.concept')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='data.person')),
                ('visit_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='data.visitoccurrence')),
            ],
            options={
                'verbose_name': 'Drug Exposure',
                'verbose_name_plural': 'Drug Exposures',
                'db_table': 'omop_drug_exposure',
                'indexes': [models.Index(fields=['person', 'drug_exposure_start_date'], name='omop_drug_e_person__c27fa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_date', models.DateField(db_index=True)),
                ('value_as_number', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('range_low', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('range_high', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('measurement_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_concept', models.ForeignKey(limit_choices_to={'domain_id': 'Measurement'}, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='data.concept')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='data.person')),
                ('visit_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='data.visitoccurrence')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'db_table': 'omop_measurement',
                'indexes': [models.Index(fields=['person', 'measurement_date'], name='omop_measur_person__1119a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureOccurrence',
            fields=[
                ('procedure_occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_date', models.DateField(db_index=True)),
                ('procedure_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='data.person')),
                ('procedure_concept', models.ForeignKey(limit_choices_to={'domain_id': 'Procedure'}, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='data.concept')),
                ('visit_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='data.visitoccurrence')),
            ],
            options={
                'verbose_name': 'Procedure Occurrence',
                'verbose_name_plural': 'Procedure Occurrences',
                'db_table': 'omop_procedure_occurrence',
                'indexes': [models.Index(fields=['person', 'procedure_date'], name='omop_proced_person__1caed0_idx')],
            },
        ),
    ]
