# Generated by Django 5.2.15 on 2026-06-25 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dataqualitylog_etllog_alter_concept_domain_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('trial_name', models.CharField(max_length=255)),
                ('trial_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('trial_start_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clinical Trial',
                'verbose_name_plural': 'Clinical Trials',
                'db_table': 'cancer_clinical_trial',
            },
        ),
        migrations.CreateModel(
            name='CancerCohort',
            fields=[
                ('cohort_id', models.AutoField(primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_stage', models.CharField(default='0', max_length=20)),
                ('max_stage', models.CharField(default='IV', max_length=20)),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=120)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer_types', models.ManyToManyField(help_text='Select cancer types to include in this cohort', limit_choices_to={'domain_id': 'Condition'}, related_name='cancer_cohorts', to='data.concept')),
            ],
            options={
                'verbose_name': 'Cancer Cohort',
                'verbose_name_plural': 'Cancer Cohorts',
                'db_table': 'cancer_cohort',
            },
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('inclusion_reason', models.CharField(choices=[('Meets criteria', 'Meets all criteria'), ('Manual add', 'Manually added'), ('Override', 'Criteria override')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cancercohort')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
            ],
            options={
                'verbose_name': 'Cohort Membership',
                'verbose_name_plural': 'Cohort Memberships',
                'db_table': 'cancer_cohort_membership',
                'unique_together': {('cohort', 'person')},
            },
        ),
        migrations.AddField(
            model_name='cancercohort',
            name='patients',
            field=models.ManyToManyField(related_name='cancer_cohorts', through='data.CohortMembership', to='data.person'),
        ),
        migrations.CreateModel(
            name='TreatmentRegimen',
            fields=[
                ('regimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('regimen_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('planned_cycles', models.IntegerField(blank=True, null=True)),
                ('completed_cycles', models.IntegerField(default=0)),
                ('best_response', models.CharField(choices=[('CR', 'Complete Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_regimens', to='data.person')),
            ],
            options={
                'verbose_name': 'Treatment Regimen',
                'verbose_name_plural': 'Treatment Regimens',
                'db_table': 'cancer_treatment_regimen',
            },
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('grade', models.CharField(choices=[('1', 'Grade 1 (Mild)'), ('2', 'Grade 2 (Moderate)'), ('3', 'Grade 3 (Severe)'), ('4', 'Grade 4 (Life-threatening)'), ('5', 'Grade 5 (Fatal)')], max_length=10)),
                ('resolution_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Resolved', 'Resolved'), ('Improving', 'Improving'), ('Worsening', 'Worsening')], default='Ongoing', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='data.person')),
                ('treatment_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_events', to='data.treatmentregimen')),
            ],
            options={
                'verbose_name': 'Adverse Event',
                'verbose_name_plural': 'Adverse Events',
                'db_table': 'cancer_adverse_event',
            },
        ),
        migrations.CreateModel(
            name='TrialEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('treatment_arm', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.clinicaltrial')),
            ],
            options={
                'db_table': 'cancer_trial_enrollment',
                'unique_together': {('trial', 'person')},
            },
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='patients',
            field=models.ManyToManyField(related_name='clinical_trials', through='data.TrialEnrollment', to='data.person'),
        ),
        migrations.CreateModel(
            name='TumorProfile',
            fields=[
                ('tumor_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('0', 'Stage 0'), ('I', 'Stage I'), ('II', 'Stage II'), ('III', 'Stage III'), ('IV', 'Stage IV'), ('Unknown', 'Unknown')], max_length=20)),
                ('histology', models.CharField(choices=[('Adenocarcinoma', 'Adenocarcinoma'), ('Squamous Cell', 'Squamous Cell'), ('Small Cell', 'Small Cell'), ('Large Cell', 'Large Cell'), ('Mesothelioma', 'Mesothelioma'), ('Other', 'Other')], max_length=100)),
                ('diagnosis_date', models.DateField()),
                ('mutation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_profiles', to='data.person')),
                ('primary_diagnosis', models.ForeignKey(limit_choices_to={'condition_concept_vocabulary_id': 'SNOMED'}, on_delete=django.db.models.deletion.PROTECT, related_name='tumor_profiles', to='data.conditionoccurrence')),
            ],
            options={
                'verbose_name': 'Tumor Profile',
                'verbose_name_plural': 'Tumor Profiles',
                'db_table': 'cancer_tumor_profile',
            },
        ),
        migrations.AddField(
            model_name='treatmentregimen',
            name='tumor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='data.tumorprofile'),
        ),
    ]
