# Generated by Django 5.2.15 on 2026-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_clinicaltrial_cancercohort_cohortmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etllog',
            name='records_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
