# Generated by Django 5.2.15 on 2026-06-29 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_etllog_records_skipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='System Identifier (REDCap, HL7, Kafka etc)', max_length=50)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Details about the data source')),
                ('connection_config', models.JSONField(blank=True, default=dict, help_text='Configuration for connecting to this source')),
                ('parser_class', models.CharField(blank=True, help_text='Full path to ETL class etl.redcap_etl.REDCapETL', max_length=255)),
                ('batch_schedule', models.CharField(blank=True, help_text='Cron expression for batch ETL', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable this source')),
                ('is_real_time', models.BooleanField(default=False, help_text='True if streaming (Kafka or HL7), False if batch CSV/JSON')),
                ('min_mapping_confidence', models.FloatField(default=0.9, help_text='Minimum confidence score for concept mappings to be used', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_unmapped_percent', models.FloatField(default=10.0, help_text='Fail ETL if more than X% of records unmapped', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_etl_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_source',
                'indexes': [models.Index(fields=['name', 'is_active'], name='data_source_name_53810c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConceptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(help_text="Code from source system (e.g., 'pembrolizumab', 'C34.1', 'PEMBRO')", max_length=100)),
                ('source_value', models.CharField(help_text="Human-readable value (e.g., 'Pembrolizumab')", max_length=255)),
                ('source_field', models.CharField(blank=True, help_text='Which field this comes from ex: drug_1_name', max_length=100)),
                ('source_vocabulary', models.CharField(blank=True, help_text='ICD10, RxNorm, LOINC, Local...', max_length=50)),
                ('mapping_type', models.CharField(choices=[('EXACT', 'Exact match - Definitely correct'), ('PARENT', 'Parent Concept - Hierarchical match'), ('FUZZY', 'Fuzzy Match - Similar names'), ('MANUAL', 'Manual Review - Human-curated')], default='EXACT', max_length=20)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in this mapping: 1.0=>certain , 0.5=guess, 0.0=wrong', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True, help_text='Why this mapping exists, any caveats,etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_concept', models.ForeignKey(help_text='Standard OMOP concept this maps to ', on_delete=django.db.models.deletion.PROTECT, related_name='source_mappings', to='data.concept')),
                ('data_source', models.ForeignKey(help_text='Which data source this mapping applies to', on_delete=django.db.models.deletion.CASCADE, related_name='concept_mappings', to='data.datasource')),
            ],
            options={
                'db_table': 'omop_concept_mapping',
                'indexes': [models.Index(fields=['data_source', 'source_code'], name='omop_concep_data_so_32084b_idx'), models.Index(fields=['data_source', 'confidence_score'], name='omop_concep_data_so_931595_idx')],
                'unique_together': {('data_source', 'source_code', 'source_value', 'source_field')},
            },
        ),
        migrations.CreateModel(
            name='UnmappedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=100)),
                ('source_value', models.CharField(blank=True, max_length=255)),
                ('source_field', models.CharField(blank=True, help_text='Which field this unmapped value came from', max_length=100)),
                ('domain_id', models.CharField(choices=[('Condition', 'Condition/Diagnosis'), ('Drug', 'Drug/Medication'), ('Measurement', 'Lab/Measurement'), ('Visit', 'Visit Type'), ('Procedure', 'Procedure'), ('Gender', 'Gender'), ('Race', 'Race/Ethnicity'), ('Other', 'Other')], max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('occurrence_count', models.IntegerField(default=1, help_text="How many times we've seen this unmapped value")),
                ('status', models.CharField(choices=[('UNRESOLVED', 'Unresolved - Needs attention'), ('MAPPED', 'Mapped - Now has ConceptMapping'), ('IGNORED', 'Ignored - Not a valid concept')], default='UNRESOLVED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Why unmapped or how it was resolved')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmapped_concepts', to='data.datasource')),
                ('resolved_to', models.ForeignKey(blank=True, help_text='Which concept this was eventually mapped to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.concept')),
            ],
            options={
                'db_table': 'omop_unmapped_concept',
                'indexes': [models.Index(fields=['data_source', 'status'], name='omop_unmapp_data_so_d6b4af_idx'), models.Index(fields=['status', 'occurrence_count'], name='omop_unmapp_status_733e38_idx')],
                'unique_together': {('data_source', 'source_code', 'domain_id')},
            },
        ),
    ]
