# Generated by Django 5.2.15 on 2026-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_datasource_conceptmapping_unmappedconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('JSON', 'JSON Files'), ('CSV', 'CSV Files'), ('HL7', 'HL7 Messages'), ('FHIR', 'FHIR API'), ('ODBC', 'ODBC Database'), ('KAFKA', 'Kafka Stream'), ('FILE', 'Custom Format')], default='JSON', max_length=20),
        ),
    ]
