# Generated by Django 5.2.15 on 2026-06-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_datasource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentregimen',
            name='best_response',
            field=models.CharField(blank=True, choices=[('CR', 'Complete Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease'), ('Unknown', 'Unknown')], default='Unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentregimen',
            name='tumor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='data.tumorprofile'),
        ),
        migrations.AlterField(
            model_name='tumorprofile',
            name='histology',
            field=models.CharField(blank=True, choices=[('Adenocarcinoma', 'Adenocarcinoma'), ('Squamous Cell', 'Squamous Cell'), ('Small Cell', 'Small Cell'), ('Large Cell', 'Large Cell'), ('Mesothelioma', 'Mesothelioma'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tumorprofile',
            name='primary_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tumor_profiles', to='data.conditionoccurrence'),
        ),
        migrations.AlterField(
            model_name='tumorprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[('0', 'Stage 0'), ('I', 'Stage I'), ('II', 'Stage II'), ('III', 'Stage III'), ('IV', 'Stage IV'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
