# Generated by Django 5.2.15 on 2026-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_treatmentregimen_best_response_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurement',
            name='omop_measur_person__1119a7_idx',
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='grade',
            field=models.CharField(choices=[('1', 'Grade 1 (Mild)'), ('2', 'Grade 2 (Moderate)'), ('3', 'Grade 3 (Severe)'), ('4', 'Grade 4 (Life-threatening)'), ('5', 'Grade 5 (Fatal)')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_source_value',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='treatmentregimen',
            name='best_response',
            field=models.CharField(blank=True, choices=[('CR', 'Complete Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tumorprofile',
            name='histology',
            field=models.CharField(blank=True, choices=[('Adenocarcinoma', 'Adenocarcinoma'), ('Squamous Cell', 'Squamous Cell'), ('Small Cell', 'Small Cell'), ('Large Cell', 'Large Cell'), ('Mesothelioma', 'Mesothelioma'), ('Other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tumorprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[('0', 'Stage 0'), ('I', 'Stage I'), ('II', 'Stage II'), ('III', 'Stage III'), ('IV', 'Stage IV'), ('Unknown', 'Unknown')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['person', 'grade'], name='cancer_adve_person__adb532_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['person', '-measurement_date'], name='omop_measur_person__ebc896_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_source_value'], name='omop_person_person__2c31f4_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['year_of_birth'], name='omop_person_year_of_03bace_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentregimen',
            index=models.Index(fields=['person', 'best_response'], name='cancer_trea_person__bb13be_idx'),
        ),
        migrations.AddIndex(
            model_name='tumorprofile',
            index=models.Index(fields=['person', 'stage'], name='cancer_tumo_person__275f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='tumorprofile',
            index=models.Index(fields=['stage', 'histology'], name='cancer_tumo_stage_bd3bce_idx'),
        ),
    ]
